//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DB_MARKET.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_MarketEntities : DbContext
    {
        public db_MarketEntities()
            : base("name=db_MarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Customer> TB_Customer { get; set; }
        public virtual DbSet<TB_ImportRecord> TB_ImportRecord { get; set; }
        public virtual DbSet<TB_Product> TB_Product { get; set; }
        public virtual DbSet<TB_ShoppingRecord> TB_ShoppingRecord { get; set; }
    }
}
