//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DB_MARKET.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Customer
    {
        public string Cid { get; set; }
        public string Cname { get; set; }
        public Nullable<int> Cdeposit { get; set; }
    }
}
